### ISSUE TITLE
MacTCP detection fails under A/UX's System 7.0.1

### ISSUE THREAD

**Issue by lausvi** [rabbitholecomputing/GetDownClassic#1]
I know this is a very rare use-case but anyway :)

Trying to launch GetDown, I get "This program requires MacTCP or Open Transport, neither of which are present on your system".

This was on my A/UX 3.1, which uses Mac OS 7.0.1 and has MacTCP-based networking stack (the control panel is greyed out as the changes are done from the Unix side). I have configured my networking and it works from the A/UX terminal. The MacTCP control panel says it's a version 1.1b1. 

I am not sure how the stack is detected, but I was wondering if this might be just an issue of not detecting this unusual version of it, and could it be perhaps modified to work under the A/UX's Mac-side too?

**Comment by aperezbios** [comment]
Thanks for the report. This is indeed a very unique use case :) While this isn't something I expect we'll fix any time soon, we'd be happy to accept any pull requests which address it.
